project:
  type: book

book: 
  title: "How to approach the definition of WUI in northern Europe"
  author: "Javier Elio, Elsa Pastor, Nieves Fernandez-Anez, Frida Vermina Plathner"
  date: today
  chapters:
    - index.qmd
    - article.qmd
    - article_codes.qmd

bibliography: references.bib
link-citations: true

format:
  html:
    embed-resources: true
    theme: cosmo
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    fig-align: center

editor: visual

execute:
  warning: false
  message: false

