project:
  type: book
  output-dir: docs

book: 
  title: "How to approach the definition of WUI in Northern Europe"
  author: "Javier Elio Medina, Frida Vermina Plathner, Elsa Pastor, Nieves Fernandez-Anez"
  date: today
  repo-url: "https://github.com/javiereliomedina/wui_definition_neur.git"
  chapters:
    - index.qmd
    - article.qmd
    - article_codes.qmd

bibliography: references.bib
link-citations: true

format:
  html:
    embed-resources: true
    theme: cosmo
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    fig-align: center

editor: visual

execute:
  warning: false
  message: false

