# Aricle

How to approach the definition of WUI in northern Europe (doi: )

## Abstract {.unnumbered}

This paper aims to delineate the wildland-urban interface in the sparsely populated, limited-resourced Scandinavian peninsula (excl. Finland). Common WUI mapping assumptions and how different thresholds capture the reality of building ignition from wildfire in this region are evaluated. We show that dedicated fuel maps capture areas at risk slightly better than vegetation maps, although the choice of map per se is less important than the selected limit for possible ember transport. The commonly used 6.17 buildings/km^2^ threshold for building density fails to capture most wildfire incidents that have led to building ignition.

## Acknowledgements {.unnumbered}

N. Fernandez-Anez acknowledges The Research Council of Norway, Project 301569: Building Design for At-risk Groups (BUILDER) for supporting her contribution. F. Vermina Plathner was supported by FORMAS \[grant number 2021-02396\]. E. Pastor acknowledges the Spanish Ministry of Science, Innovation and Universities, Project PID2023-150607OB-I00.
